Update cpu_benchmarks.yml

diff --git a/.github/workflows/cpu_benchmarks.yml b/.github/workflows/cpu_benchmarks.yml
--- a/.github/workflows/cpu_benchmarks.yml
+++ b/.github/workflows/cpu_benchmarks.yml
@@ -32,9 +32,9 @@ jobs:
             pretty_name: "XLA Linux x86 CPU",
           },
           {
-            os: "linux-arm64-c4a-16",
+            os: "arc-linux-arm64-c4a-64-dev", # "linux-arm64-c4a-16",
             container: "us-central1-docker.pkg.dev/tensorflow-sigs/tensorflow/ml-build-arm64:latest",
-            pretty_name: "XLA Linux ARM64 CPU",
+            pretty_name: "XLA Linux ARM64 CPU DEV",
           }
         ]
     name: ${{ matrix.job_info.pretty_name }}
@@ -52,18 +52,18 @@ jobs:
           df -h    # Disk space information
           uname -a # Kernel information
 
-      - name: Check Python Version in Container
-        run: python3 --version
+      # - name: Check Python Version in Container
+      #   run: python3 --version
 
-      - name: Install Python 3.10 if not present (IN CONTAINER)
-        run: |
-          if ! python3 --version > /dev/null 2>&1; then # check for python3
-            echo "Python 3 not found, installing..."
-            apt-get update
-            apt-get install -y python3.10 python3-pip
-          else
-            echo "Python 3 found."
-          fi
+      # - name: Install Python 3.10 if not present (IN CONTAINER)
+      #   run: |
+      #     if ! python3 --version > /dev/null 2>&1; then # check for python3
+      #       echo "Python 3 not found, installing..."
+      #       apt-get update
+      #       apt-get install -y python3.10 python3-pip
+      #     else
+      #       echo "Python 3 found."
+      #     fi
 
       - name: Checkout OpenXLA
         uses: actions/checkout@v3
@@ -75,17 +75,17 @@ jobs:
         run:
           mkdir results
 
-      - name: Run setup.sh for E2E benchmarks flax_2b
-        working-directory: xla/backends/cpu/benchmarks/e2e/gemma2/flax_2b
-        timeout-minutes: 60
-        run: |
-          bash setup.sh
+      # - name: Run setup.sh for E2E benchmarks flax_2b
+      #   working-directory: xla/backends/cpu/benchmarks/e2e/gemma2/flax_2b
+      #   timeout-minutes: 60
+      #   run: |
+      #     bash setup.sh
 
-      - name: Run run.sh for E2E benchmarks flax_2b
-        working-directory: xla/backends/cpu/benchmarks/e2e/gemma2/flax_2b
-        timeout-minutes: 30
-        run: |
-          bash run.sh | tee -a ../../../../../../results/flax_2b.log
+      # - name: Run run.sh for E2E benchmarks flax_2b
+      #   working-directory: xla/backends/cpu/benchmarks/e2e/gemma2/flax_2b
+      #   timeout-minutes: 30
+      #   run: |
+      #     bash run.sh | tee -a ../../../../../../results/flax_2b.log
 
       # TODO(juliagmt): Re-enable once the build is fixed.
       # - name: Build run_hlo_module
@@ -107,29 +107,29 @@ jobs:
       #       ./bazel-bin/xla/tools/run_hlo_module --input_format=hlo --platform=CPU "$file"
       #     done
 
-      # - name: Build CPU Benchmarks
-      #   working-directory: xla
-      #   run: bazel build -c opt --dynamic_mode=off //xla/backends/cpu/benchmarks:*
+      - name: Build CPU Benchmarks
+        working-directory: xla
+        run: bazel build -c opt --dynamic_mode=off //xla/backends/cpu/benchmarks:*
 
-      # - name: Run CPU benchmarks
-      #   working-directory: xla
-      #   continue-on-error: true
-      #   run: |
-      #     find ./bazel-bin/xla/backends/cpu/benchmarks/ -maxdepth 1 -type f -executable -name "*_test" -print0 | while IFS= read -r -d $'\0' benchmark; do
-      #       benchmark_name=$(basename "$benchmark" | sed 's/_test$//') 
-      #       echo "Running benchmark: $benchmark_name"
+      - name: Run CPU benchmarks
+        working-directory: xla
+        continue-on-error: true
+        run: |
+          find ./bazel-bin/xla/backends/cpu/benchmarks/ -maxdepth 1 -type f -executable -name "*_test" -print0 | while IFS= read -r -d $'\0' benchmark; do
+            benchmark_name=$(basename "$benchmark" | sed 's/_test$//') 
+            echo "Running benchmark: $benchmark_name"
 
-      #       # Run the benchmark with default parameters.
-      #       $benchmark --benchmark_filter=".*"
-      #       $benchmark --benchmark_filter=".*" > "results/$benchmark_name.log" 2>&1
+            # Run the benchmark with default parameters.
+            $benchmark --benchmark_filter=".*"
+            $benchmark --benchmark_filter=".*" > "results/$benchmark_name.log" 2>&1
 
-      #       # Check the exit code of the benchmark
-      #       if [ $? -ne 0 ]; then
-      #         echo "Error: Benchmark '$benchmark_name' failed. Check the log file: results/$benchmark_name.log"
-      #       else
-      #         echo "Benchmark '$benchmark_name' completed successfully."
-      #       fi
-      #     done
+            # Check the exit code of the benchmark
+            if [ $? -ne 0 ]; then
+              echo "Error: Benchmark '$benchmark_name' failed. Check the log file: results/$benchmark_name.log"
+            else
+              echo "Benchmark '$benchmark_name' completed successfully."
+            fi
+          done
       - name: Upload Results ${{ matrix.build_target }}
         uses: actions/upload-artifact@v4
         with:
